kind: pipeline
type: docker
name: default
steps:
  - name: build-all
    image: maven:3-jdk-11
    volumes:
      - name: mvncache
        path: /root/.m2
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - cp efluid-datagate-app/src/docker/build-ci/* efluid-datagate-app/target
  #  - name: test-all
  #    image: maven:3-jdk-11
  #    volumes:
  #      - name: mvncache
  #        path: /root/.m2
  #    commands:
  #      - mvn test
  - name: docker
    image: plugins/docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    settings:
      dockerfile: efluid-datagate-app/target/Dockerfile
      repo: 172.17.0.1:5000/datagate/latest
      registry: 172.17.0.1:5000
      insecure: true
  - name: notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: datagate-build
      template: >
        {{#success build.status}}
          Datagate build of commit `${DRONE_COMMIT_MESSAGE}` on branch `${DRONE_COMMIT_BRANCH}` succeeded
        {{else}}
          Datagate build of commit `${DRONE_COMMIT_MESSAGE}` on branch `${DRONE_COMMIT_BRANCH}` failed
        {{/success}}
    when:
      status:
        - success
        - failure

volumes:
  - name: mvncache
    host:
      path: /opt/server/build/repository
  - name: dockersock
    host:
      path: /var/run/docker.sock