kind: pipeline
name: default

steps:
- name: build-all
  image: maven:3-jdk-11
  volumes:
    - name: mvncache
      path: /root/.m2
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- name: test-all
  image: maven:3-jdk-11
  volumes:
    - name: mvncache
      path: /root/.m2
  commands:
  - mvn test
- name: notification
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: datagate-build
    template: >
      {{#success build.status}}
        Datagate build of commit {{build.ref}} on branch {{build.branch}} succeeded
      {{else}}
        Datagate build of commit {{build.ref}} on branch {{build.branch}} failed
      {{/success}}

volumes:
  - name: mvncache
    host:
      path: /opt/server/build/repository