version: '2'

services:
    efluid-datagate-gest:
        image: efluid-datagate-gest:latest
        restart: always
        ports:
        - 8080:8080
        volumes:
        - /instance/application.yml:/cfg/application.yml:ro
        - /instance/logs:/tmp
        - /instance/tmp:/logs
        container_name: efluid-datagate-gest-struff
