---
## PARAMETER MANAGER CONFIG
param-efluid:

   managed-datasource:
       driverClassName: org.postgresql.Driver
       url: jdbc:postgresql://localhost/demo
       username: user
       password: user

   details:
       version: 1.1.1

## TECH FEATURES CUSTOM
spring:
    profiles:
        active: demo

    thymeleaf:
        cache: false

    datasource:
        url: jdbc:postgresql://localhost/manager
        username: user
        password: user
        driver-class-name: org.postgresql.Driver

    jpa:
        show-sql: true
        hibernate:
           ddl-auto: create

## WEB SERVER CONFIG
server:
    contextPath:
    port: 8080