---
param-efluid:

    managed-datasource:
       driver-class-name: oracle.jdbc.OracleDriver
       url: jdbc:oracle:thin:@LPBDDEDT4:2483/DTGTEDT1
       username: DATAGATE_SRC_FLD
       password: Its4bdd_DATAGATE_SRC_FLD
       meta:
           filterSchema: DATAGATE_SRC_FLD
           preload: true
           fixed-cached: false
       
    security:
        salt: 12345678901234567890123456789012
       
    details:
        instance-name: SOURCE
    
## TECH FEATURES CUSTOM
spring:
    profiles:
        active: prod
    
    datasource:
        url: jdbc:h2:~\h2-test;DB_CLOSE_ON_EXIT=TRUE
        username: sa
        password: 
        driver-class-name: org.h2.Driver
    
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create
    
## WEB SERVER CONFIG
server:
    port: 8080