version: '2'

services:
    param-gest:
        image: param-gest:latest
        restart: always
        ports:
        - 8080:8080
        volumes:
        - /instance/application.yml:/cfg/application.yml:ro
        - /instance/logs:/tmp
        - /instance/tmp:/logs
        container_name: param-gest-struff
